{
 "title": "Alert Center",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Dashboard List", "type": "dashlist", "gridPos": { "h": 6, "w": 23, "x": 0, "y": 0 } },
  { "title": "Mesos Agent Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Unreachable Agents",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_slaves_unreachable{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Deactivated Agents",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 11, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_slaves_inactive{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Cluster CPU Allocation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    { "expr": "mesos_master_cpus_percent" }
   ]
  },
  {
   "title": "Cluster Memory Allocation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    { "expr": "mesos_master_mem_percent" }
   ]
  },
  {
   "title": "Cluster Storage Allocation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    { "expr": "mesos_master_disk_percent" }
   ]
  },
  {
   "title": "CPU Usage % (total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max by(instance)(cpu_usage_system + cpu_usage_user + cpu_usage_guest)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "max by(instance)(mem_active)", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Mesos Task Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Tasks Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_tasks_failed{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Tasks Lost",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_tasks_lost{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Tasks Unreachable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_tasks_unreachable{state=\"leader\"}"
    }
   ]
  },
  { "title": "Mesos Framework Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Inactive Frameworks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mesos_master_frameworks_inactive{state=\"leader\"}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } }
 ]
}