{
 "title": "Alert Center",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Dashboard List", "type": "dashlist", "gridPos": { "h": 6, "w": 23, "x": 0, "y": 0 } },
  { "title": "Mesos Agent Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Unreachable Agents",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_slaves_unreachable"
    }
   ]
  },
  {
   "title": "Deactivated Agents",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mesos_master_slaves_inactive" }
   ]
  },
  { "title": "Mesos Task Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Tasks Failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mesos_master_tasks_failed" }
   ]
  },
  {
   "title": "Tasks Killed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mesos_master_tasks_killed" }
   ]
  },
  {
   "title": "Tasks Unreachable",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mesos_master_tasks_unreachable" }
   ]
  },
  { "title": "Mesos Framework Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Inactive Frameworks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mesos_master_frameworks_inactive"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } }
 ]
}