#!/bin/bash
#set -x #echo on

echo "Running command: dcos package list to see the current running version of Kubernetes"
dcos package list

echo "Running command: dcos package describe kubernetes --package-versions to list available package versions"
dcos package describe kubernetes --package-versions

read -p 'What version of Kubernetes to upgrade/downgrade to?: ' K8SVERSION
        K8SVERSION=$K8SVERSION

dcos package uninstall kubernetes --cli
dcos package install kubernetes --cli --yes --package-version=$K8SVERSION

#Upgrading/Downgrading Kubernetes
dcos kubernetes update --package-version=$K8SVERSION

#Show version
dcos package list
