{
 "title": "SDK",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "LaunchGroups [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "launches/s" }
   ],
   "targets": [
    {
     "expr": "rate(operation_launch_group[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LaunchGroups [1m] (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "launches/s" }
   ],
   "targets": [
    {
     "expr": "rate(operation_launch_group[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Processed Offers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    { "expr": "rate(offers_processed[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Processed Offers [1m] (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    { "expr": "rate(offers_processed[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Received Offers [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    { "expr": "rate(offers_received[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Received Offers [1m] (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "offers/s" }
   ],
   "targets": [
    { "expr": "rate(offers_received[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Revives [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "revives/s" }
   ],
   "targets": [
    { "expr": "rate(revives[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Short Declines [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "declines/s" }
   ],
   "targets": [
    { "expr": "rate(declines_short[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Long Declines [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "declines/s" }
   ],
   "targets": [
    { "expr": "rate(declines_long[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Revives (cumulative)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "revives/s" }
   ],
   "targets": [
    { "expr": "revives", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Short Declines [1m] (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "declines/s" }
   ],
   "targets": [
    { "expr": "rate(declines_short[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Long Declines [1m] (cumulative)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "declines/s" }
   ],
   "targets": [
    { "expr": "rate(declines_long[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "ProcessOffers Median",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "offers_process{quantile=\"0.5\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}