{
 "title": "DC/OS Dashboard",
 "time": { "from": "2018-08-18T23:35:57.576Z", "to": "2018-08-20T23:35:57.584Z" },
 "panels": [
  {
   "title": "CPU_total",
   "type": "graph",
   "description": "Percentage of CPUs used.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "cpu_total" }
   ]
  },
  {
   "title": "CPU_idle",
   "type": "graph",
   "description": "Percentage of CPUs Idle",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "cpu_idle" }
   ]
  },
  {
   "title": "memory_free",
   "type": "graph",
   "description": "Total free memory in bytes per agent",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "memory_free" }
   ]
  },
  {
   "title": "memory_cached",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "memory_cached" }
   ]
  },
  {
   "title": "Load_15min",
   "type": "graph",
   "description": "Load average for the past 15 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "expr": "load_15min" }
   ]
  },
  {
   "title": "process_count",
   "type": "graph",
   "description": "Number of processes that are running",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_count" }
   ]
  },
  {
   "title": "filesystem_capacity_free",
   "type": "graph",
   "description": "Amount of available capacity in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "filesystem_capacity_free" }
   ]
  },
  {
   "title": "filesystem_capacity_used",
   "type": "graph",
   "description": "Capacity used in bytes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "filesystem_capacity_used" }
   ]
  }
 ]
}