{
 "title": "DC/OS Overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Cluster Name", "type": "text", "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 }, "content": "# Demo Cluster" },
  {
   "title": "Active Agents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "mesos_master_slaves_active" }
   ]
  },
  {
   "title": "Active Frameworks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "mesos_master_frameworks_active" }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "mesos_master_tasks_running" }
   ]
  },
  {
   "title": "CPU Usage % (total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(cpu_usage_user + cpu_usage_guest)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage (total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "mem_active", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Disk Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "disk_used" }
   ]
  }
 ]
}