{
 "title": "Mesos Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tasks Staging",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mesos_master_tasks_staging" }
   ]
  },
  {
   "title": "Tasks Starting",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mesos_master_tasks_starting" }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mesos_master_tasks_running" }
   ]
  },
  {
   "title": "Tasks Killing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mesos_master_tasks_killing" }
   ]
  },
  {
   "title": "Tasks Killed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mesos_master_tasks_killed" }
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mesos_master_tasks_failed" }
   ]
  },
  {
   "title": "Tasks Lost",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mesos_master_tasks_lost" }
   ]
  },
  {
   "title": "Tasks Unreachable",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mesos_master_tasks_unreachable" }
   ]
  },
  { "title": "Frameworks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Declined Offers (per framework)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_frameworks_offers_declined",
     "legendFormat": "{{framework_name}}"
    }
   ]
  },
  {
   "title": "Accepted Offers (per framework)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_frameworks_offers_accepted",
     "legendFormat": "{{framework}}"
    }
   ]
  },
  {
   "title": "Mesos Allocator run (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_mesos_allocation_run_ms",
     "legendFormat": "Allocation"
    },
    {
     "expr": "mesos_allocator_mesos_allocation_run_latency_ms",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}