{
 "title": "Mesos Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Declined Offers (per framework)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_frameworks_offers_declined",
     "legendFormat": "{{framework_name}}"
    }
   ]
  },
  {
   "title": "Accepted Offers (per framework)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_frameworks_offers_accepted",
     "legendFormat": "{{framework}}"
    }
   ]
  },
  {
   "title": "Mesos Allocator run (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_mesos_allocation_run_ms",
     "legendFormat": "Allocation"
    },
    {
     "expr": "mesos_allocator_mesos_allocation_run_latency_ms",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}