{
 "title": "Nodes Overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "description": "Allocation and utilization",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(cpu_usage_system + cpu_usage_user + cpu_usage_guest)",
     "legendFormat": "{{instance}}"
    },
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(mem_used_percent)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(disk_used_percent)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum by(instance)(gpu)" }
   ]
  },
  {
   "title": "Connected Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "3", "legendFormat": "Nodes" }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "count by(task_name)(task_status_task_running)",
     "legendFormat": "{{task_name}}"
    }
   ]
  }
 ]
}